version: '3.8'

services:
  namenode:
    build:
      context: ./namenode
    container_name: namenode
    restart: on-failure
    ports:
      - 9870:9870
      - 9000:9000
      - 80:9870
    volumes:
      - hadoop_namenode:/hadoop/dfs/name
    environment:
      - CLUSTER_NAME=test
    env_file:
      - ./hadoop.env

  datanode1:
    build:
      context: ./datanode
    container_name: datanode1
    hostname: datanode1
    restart: on-failure
    ports:
      - 9866:9866
      - 9864:9864
    volumes:
      - hadoop_datanode1:/hadoop/dfs/data
    environment:
      SERVICE_PRECONDITION: "namenode:9870"
    env_file:
      - ./hadoop.env
    depends_on:
      - namenode

  datanode2:
    build:
      context: ./datanode
    container_name: datanode2
    hostname: datanode2
    restart: on-failure
    ports:
      - 9867:9866
      - 9863:9864
    volumes:
      - hadoop_datanode2:/hadoop/dfs/data
    environment:
      SERVICE_PRECONDITION: "namenode:9870"
    env_file:
      - ./hadoop.env
    depends_on:
      - namenode

  datanode3:
    build:
      context: ./datanode
    container_name: datanode3
    hostname: datanode3
    restart: on-failure
    ports:
      - 9868:9866
      - 9862:9864
    volumes:
      - hadoop_datanode3:/hadoop/dfs/data
    environment:
      SERVICE_PRECONDITION: "namenode:9870"
    env_file:
      - ./hadoop.env
    depends_on:
      - namenode

  resourcemanager:
    build:
      context: ./resourcemanager
    container_name: resourcemanager
    restart: on-failure
    ports:
      - 8088:8088
    environment:
      SERVICE_PRECONDITION: "namenode:9870 datanode1:9864 datanode2:9864 datanode3:9864"
    env_file:
      - ./hadoop.env
    depends_on:
      - namenode
      - datanode1
      - datanode2
      - datanode3

  nodemanager:
    build:
      context: ./nodemanager
    container_name: nodemanager
    restart: on-failure
    environment:
      SERVICE_PRECONDITION: "namenode:9870 datanode1:9864 datanode2:9864
        datanode3:9864 resourcemanager:8088"
    env_file:
      - ./hadoop.env
    depends_on:
      - namenode
      - datanode1
      - datanode2
      - datanode3

  historyserver:
    build:
      context: ./historyserver
    container_name: historyserver
    restart: on-failure
    ports:
      - 8188:8188
    environment:
      SERVICE_PRECONDITION: "namenode:9870 datanode1:9864 datanode2:9864
        datanode3:9864 resourcemanager:8088"
    volumes:
      - hadoop_historyserver:/hadoop/yarn/timeline
    env_file:
      - ./hadoop.env
    depends_on:
      - namenode
      - datanode1
      - datanode2
      - datanode3

volumes:
  hadoop_namenode: null
  hadoop_datanode1: null
  hadoop_datanode2: null
  hadoop_datanode3: null
  hadoop_historyserver: null
